### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by farzher** [gladkikhartem/koshare-router#3]
This used to work, now it says `WebSocket connection to 'ws://104.196.187.4:8888/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Did i get blocked? Is it dead?

**Comment by gladkikhartem** [comment]
Sorry, my bad,
Server was restarted for maintenance reasons and I've forgot to add router to startup script.
Now everything is running as usual. 
Happy New Year!
